/*
 * Copyright (c) Vinícius Bastos da Silva 2026
 * This file is part of ResultPattern.
 * Licensed under the GNU Lesser General Public License v3 (LGPL v3).
 * See the LICENSE file in the project root for full details.
*/

using ViniBas.ResultPattern.AspNet.BuildTimeScript.Builders;
using ViniBas.ResultPattern.AspNet.BuildTimeScript.Builders.MatchMethod;
using ViniBas.ResultPattern.AspNet.BuildTimeScript.UnitTests.Helpers;

namespace ViniBas.ResultPattern.AspNet.BuildTimeScript.UnitTests.Builders;

public class MatchResultsClassBuilderTests
{
    private static MatchResultsClassParamsBuilder Params() => MatchResultsClassParamsBuilder.Create();

    private static MatchMethodBuilder CreateMethod(bool isAsync = false)
        => new(MatchMethodParamsBuilder.Create()
            .Set(p => p.IsAsync, isAsync)
            .Build());

    [Fact]
    public void Build_ShouldAssembleClassWithImportsNamespaceAndMethods()
    {
        var result = new MatchResultsClassBuilder(Params().Build()).Build();

        Assert.Contains("using Microsoft.AspNetCore.Mvc;", result);
        Assert.Contains("namespace TestNamespace;", result);
        Assert.Contains("public static class TestExtensions", result);
        Assert.Contains("private static IMatcher Matcher => Factory.GetMatcher;", result);
        Assert.Contains("public static IActionResult Match(", result);
    }

    [Fact]
    public void Build_WithMultipleMethods_ShouldContainBothMethods()
    {
        var @params = Params()
            .Set(p => p.Methods, [CreateMethod(isAsync: false), CreateMethod(isAsync: true)])
            .Build();

        var result = new MatchResultsClassBuilder(@params).Build();

        Assert.Contains("public static IActionResult Match(", result);
        Assert.Contains("public static Task<IActionResult> MatchAsync(", result);
    }

    [Fact]
    public void Build_ShouldStartWithAutoGeneratedHeader()
    {
        var result = new MatchResultsClassBuilder(Params().Build()).Build();

        Assert.StartsWith("// <auto-generated/>", result);
        Assert.Contains("#nullable enable", result);
    }
}
